services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: lazyjobsearch-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lazyjobsearch
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lazyjobsearch"]
      interval: 5s
      retries: 10
      timeout: 3s
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: lazyjobsearch-redis
    ports:
      - "6379:6379"

  minio:
    image: quay.io/minio/minio:RELEASE.2024-08-17T01-00-00Z
    container_name: lazyjobsearch-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lazyjobsearch-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      LJS_DB_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/lazyjobsearch
      PYTHONPATH: /app
    working_dir: /app
    volumes:
      - .:/app:delegated
    command: bash scripts/init_and_hold.sh

volumes:
  postgres_data:
  minio_data: