name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e .[dev]
      - name: Run tests
        env:
          LJS_DB_URL: sqlite+pysqlite:///:memory:
        run: |
          pytest --maxfail=1 --disable-warnings
      - name: Schema doc validation
        run: |
          python scripts/validate_schema_docs.py
